### PR TITLE
Update to Go 1.19.4

### PR DESCRIPTION
**Pull request by seanmalloy**
Dockerfile was updated in #83

### CODE REVIEW

**Comment by seanmalloy** [comment]
@vinny-sabatini the branch protection settings need to be updated again.

**Comment by vinny-sabatini** [comment]
@seanmalloy what would your opinion be on removing Go version 1.18.x from the CI matrix and only using Go version 1.19.x?

**Comment by seanmalloy** [comment]
> @seanmalloy what would your opinion be on removing Go version 1.18.x from the CI matrix and only using Go version 1.19.x?

I have no problem with that. Do you want me to do that in this PR or a separate PR?

**Comment by vinny-sabatini** [comment]
I'd vote let's just do it in this PR

**Comment by seanmalloy** [comment]
> I'd vote let's just do it in this PR

Updated in commit 29155473adad91f4067861aa9333b685b48ab1f4.

**Review by vinny-sabatini — APPROVED** [review]

**Pull request merged**
